### ISSUE TITLE
bug: CLI Create Theme command | AxiosError: timeout of 20000ms exceeded

### ISSUE THREAD

**Issue by ahmedrowaihi** [SallaApp/Salla-CLI#10]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

The CLI hangs when creating a theme, the repo gets initialized on my GitHub repo but CLI is not reflecting.
![image](https://user-images.githubusercontent.com/67356781/198001284-9853608b-2c94-4089-b9e0-40b9efdf25d6.png)

### Expected Behavior

Complete the CLI theme-creating process.

### Steps to Reproduce

 - install salla-cli
 ```bash
 npm install @salla.sa/cli -g
```
- create theme using salla-cli
```bash
salla theme create
```
- choose to create the theme and fill in theme information and hit ``` Enter ```

### Salla Info

[Salla info]

version: 1.4.34      
npm version: 8.19.2
node version: v18.12.0
php version: 8.1.12
os: win32
os version: 10.0.19044
user id: 126996450
uuid: 1657356D-BD81-494B-BACC-F86C20D7EAE3

**Comment by KernelCode** [comment]
Hello Ahmed,

Thank you for reporting this bug .. 
is the problem still persists ? .. as we think it's a connection problem .

**Comment by ahmedrowaihi** [comment]
yes, it's working, I updated cli as well
```
from 1.4.35 into version: 1.4.35
```
all is good.
Thanks!
