### ISSUE TITLE
Can't create theme there isn't My Theme Link in nav menu

### ISSUE THREAD

**Issue by shqawe1** [SallaApp/Salla-CLI#11]
Hi,

I'm trying to create theme but when i start creating theme cli  ask me to connect my account to github and redirect me to salla partners dashboard and as docs says i should have **My Theme** link in the main navigation menu but i don't have that link in my cp. 

Salla Info:
version: 1.4.35
npm version: 8.19.1
node version: v18.9.0
php version: 7.4.32
os: linux
os version: 5.10.0-19-amd64

**Comment by shqawe1** [comment]
Any update for this issue?

**Comment by TheYass1n** [comment]
facing the same issues
