### ISSUE TITLE
bug: Github account is not linked

### ISSUE THREAD

**Issue by alive2tinker** [SallaApp/Salla-CLI#16]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

When I attempt to create theme using salla-cli `salla theme create` I get the following error
![image](https://user-images.githubusercontent.com/10200075/224563805-ccf60b31-5321-4515-af4d-991c9659caa3.png)

even though I have been logged in using salla cli and my account is linked to github properly
![image](https://user-images.githubusercontent.com/10200075/224563755-1f5a1804-263d-4866-8413-7ff1f6414225.png)

### Expected Behavior

I should be able to create a theme and start coding right away

### Steps to Reproduce

attempt to create new theme using salla cli 

### Salla Info

C:\laragon\www
λ salla info

[Salla info]

version: 1.4.56
npm version: 8.18.0
node version: v18.8.0
php version: 8.1.10
os: win32
os version: 10.0.19045
user id:
uuid: 61DE5869-29ED-47D0-89FA-1BDF03B1858F

C:\laragon\www
λ

**Comment by jalmatari** [comment]
It fixed now, thank you for your report. if you still face the issue you can re-open the issue, or contact us in Telegram https://t.me/salladev/10573
