### ISSUE TITLE
bug: Stuck on Authentication

### ISSUE THREAD

**Issue by gharams19** [SallaApp/Salla-CLI#20]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [ ] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

When I try to login through command line salla login or any other command like salla theme preview, it takes me to the browser, I login, get the prompt that it was successfully authenticated but when I return to terminal, its stuck on
 **Waiting for authentication ...**
 then I get

 INFO  To complete the login process, you will be redirected to your browser to signin with your Salla Partners account.
                     
 WARN  ⌛ Timeout reached, please try again.
                     
 WARN  If this error persists, please visit https://github.com/SallaApp/salla-cli/issues and submit an issue.

### Expected Behavior

It logs in

### Steps to Reproduce

type salla login

### Salla Info

[Salla info]
                     
version: 1.4.57
npm version: 9.5.0
node version: v18.15.0
php version: PHP
os: darwin
os version: 20.6.0
user id: 
uuid:

**Comment by murtazablt** [comment]
I have been attempting to set up a development environment locally, but I have encountered similar issue with authentication. Installing php and adding it to the environment paths fixed my problem. 

https://www.php.net/downloads.php

**Comment by Nabute** [comment]
It has been resolved now. Thank you for your patience.
