### ISSUE TITLE
bug: TypeError: Cannot read properties of undefined (reading 'body')

### ISSUE THREAD

**Issue by arsibux** [SallaApp/Salla-CLI#21]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

App

### Current Behavior

Unable to execute the `salla app serve --port 8081`.
![image](https://user-images.githubusercontent.com/9518132/235422399-6aebb3d2-63ec-4146-9e4c-49a10c9c6d71.png)

### Expected Behavior

It should execute the cli command.

### Steps to Reproduce

After installation just run the serve command `salla app server --port 8081`

### Salla Info

salla app serve --port 8081
![image](https://user-images.githubusercontent.com/9518132/235422546-56dfb1b5-ef13-4072-a5df-dfc5ab1b1e70.png)

**Comment by jalmatari** [comment]
It fixed now, thank you for your report.
