### ISSUE TITLE
bug: NgrokClientError: failed to start tunnel

### ISSUE THREAD

**Issue by fademohsen** [SallaApp/Salla-CLI#23]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [ ] v1.x

### Salla CLI issue Type

App

### Current Behavior

when I run this command salla app serve 
I receive this error  

⠋ Starting ngrok. Please hold on ... ERROR  Oops! There is an error while serving your Salla App .
NgrokClientError: failed to start tunnel

 ERROR  Error: Oops! There is an error while serving your Salla App .

### Expected Behavior

I expected my app to serve

### Steps to Reproduce

just run salla app serve

### Salla Info

salla info

[Salla info]

version: 1.4.58
npm version: 8.19.3
node version: v18.13.0
'php' is not recognized as an internal or external command,
operable program or batch file.

 ERROR  Error: Command failed: php -v
'php' is not recognized as an internal or external command,
operable program or batch file.

 WARN  If this error persists, please visit https://github.com/SallaApp/salla-cli/issues and submit an issue.

**Comment by jalmatari** [comment]
Hello Fadi
Fixed in the new release
make sure to upgrade to the latest version 1.4.60
