### ISSUE TITLE
Issue while creating webhooks. error !! Please enter a valid webhook name. Example: 'app.installed'

### ISSUE THREAD

**Issue by ouzzall** [SallaApp/Salla-CLI#24]
When i create new webhook for my app. it is giving me error. i tried again and again but still it is giving error. i have installed the latest SallaCli package from npm. my error photo is attached
![error](https://github.com/SallaApp/Salla-CLI/assets/75587335/ce9b5f14-8ce7-415c-9984-58e09a8949b7)

**Comment by mAghaDash** [comment]
> 

any updates ?

**Comment by jalmatari** [comment]
Hello @mAghaDash, Thanks for your report on this issue.
It's fixed now, you can upgrade your CLI to the latest version, then try,

If you faced any issue, please recontact with us.

**Comment by SaddamMohsen** [comment]
i have the same issue @jalmatari 
version  Version: 3.2.2
