### ISSUE TITLE
Salla create theme , import from github

### ISSUE THREAD

**Issue by jeekooo** [SallaApp/Salla-CLI#27]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

![image](https://github.com/SallaApp/Salla-CLI/assets/8994555/62d38d8e-2135-471e-9857-20b92e6a39b9)

### Expected Behavior

I need clearable steps to import theme HTML theme from Github to Salla 

### Steps to Reproduce

I need clearable steps to import theme HTML theme from Github to Salla 

### Salla Info

[Salla info]

version: 1.4.61
npm version: 9.5.0
node version: v18.14.2
'php' is not recognized as an internal or external command,
operable program or batch file.

 ERROR  Error: Command failed: php -v
'php' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Nabute** [comment]
@jeekooo can you please provide me with the steps to reproduce this issue? And please make sure you are importing a valid salla theme (i.e. twilight.json file for instance)
