### ISSUE TITLE
bug: CLI fails to create app

### ISSUE THREAD

**Issue by MhndMousa** [SallaApp/Salla-CLI#30]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

App

### Current Behavior

After finishing my profile setup and logging in via `salla login`

Following salla's documentation by creating an application through the online wizard

I'm getting the following error when creating a new application in the terminal

Both command line and terminal are returning the same error 

![image](https://github.com/SallaApp/Salla-CLI/assets/15264541/a0036ed3-997b-4928-b9fd-ef4dbdbc949b)

### Expected Behavior

Create a new application boilerplate

### Steps to Reproduce

Simply just create a new app via `salla app create`

### Salla Info

[Salla info]

version: 3.2.0
npm version: 9.8.1
node version: v18.17.0
php version: 8.2.4
os: win32
os version: 10.0.22621
user id: 2007218996
uuid: 8A69DE79-8D5F-4798-AAAB-74D661F8827F

### Additional Information

I'm using Windows 11

**Comment by CW-SA** [comment]
Facing the same issue with "salla theme preview"

<img width="500px" alt="image" src="https://github.com/SallaApp/Salla-CLI/assets/141678190/510f1a03-6ea2-4294-a7cc-d27034a3e851">

multiple tries of the traditional support methods (login/logout/create/delete etc.), but I am still getting the same error

**Comment by cgdmohamed** [comment]
same issue creating theme with/out administrative privileges
![Screenshot 2023-08-10 212630](https://github.com/SallaApp/Salla-CLI/assets/16435049/48f0c0a5-38e4-4409-bb33-cce00c54e60a)

**Comment by MhndMousa** [comment]
I was able to workaround it by force installing salla CLI version 1.4.62. 

try `npm install @salla.sa/cli@1.4.62 -g`

**Comment by Nabute** [comment]
It has been resolved with the latest update. Please update to V3.2.1.
