### ISSUE TITLE
bug: TypeError: a.prompt is not a function

### ISSUE THREAD

**Issue by OmarAfet** [SallaApp/Salla-CLI#31]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

When I run the npx salla theme preview command, the CLI displays an error message and fails to request a preview for the theme. The specific error message reads: `The CLI failed to request preview for the Theme. Try again later. TypeError: a.prompt is not a function.`

### Expected Behavior

I expected the `salla theme preview` command to build and deploy my Salla Store Theme locally and provide a preview URL where I could see and interact with the theme in a web browser.

### Steps to Reproduce

1. Open a terminal window.
2. Navigate to the directory where my Salla Store Theme project is located.
3. Run the command npx salla theme preview.
4. Observe the output in the terminal, including the error message.
5. Attempt to access the provided preview URL in a web browser, but the URL is not accessible and the theme is not displayed.

### Salla Info
```
[Salla info]

version: 3.2.0       
npm version: 8.19.2
node version: v18.12.1
'php' is not recognized as an internal or external command,
operable program or batch file.

 ERROR  Error: Command failed: php -v
'php' is not recognized as an internal or external command,
operable program or batch file.
```
### Additional Information

```
> npx salla theme preview

        _____       _ _          _____ _      _____ 
       / ____|     | | |        / ____| |    |_   _|
      | (___   __ _| | | __ _  | |    | |      | |  
       \___ \ / _` | | |/ _` | | |    | |      | |  
       ____) | (_| | | | (_| | | |____| |____ _| |_ 
      |_____/ \__,_|_|_|\__,_|  \_____|______|_____|
    
                     Version: 3.2.0
        The Official Salla Command Line Interface

 INFO  Read the docs: https://github.com/SallaApp/Salla-CLI/ 
 INFO  Support and bugs: https://github.com/SallaApp/Salla-CLI/issues 

 INFO  run checks: 
     ✓ twilight.json was found.
     ✓ Github account is linked.
     ✓ Theme ID exists.
     ✓ The theme folder is linked to GitHub repository.

 INFO  Getting your demo stores from your account...

Listed below are the stores assoicated with your Salla Partners account ..
You can either select an existing store or create a new store in simple steps

 ERROR  The CLI failed to request preview for the Theme. Try again later.
TypeError: a.prompt is not a function

 ERROR  Error: The CLI failed to request preview for the Theme. Try again later.

 WARN  If this error persists, please visit https://github.com/SallaApp/salla-cli/issues and submit an issue.
```

**Comment by CW-SA** [comment]
facing the same issue here as well

![image](https://github.com/SallaApp/Salla-CLI/assets/141678190/c8ccbf36-6162-4c37-a85c-040d2c96faa3)

**Comment by MhndMousa** [comment]
I was able to workaround it by force installing salla CLI version 1.4.62. 

try `npm install @salla.sa/cli@1.4.62 -g`

**Comment by Nabute** [comment]
It has been resolved with the latest update. Please update to V3.2.1.
