### ISSUE TITLE
bug: An error occured while making the request to create the Theme.

### ISSUE THREAD

**Issue by aimdexter** [SallaApp/Salla-CLI#33]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [ ] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

When i try to create a new theme for a github organization I am getting this error : Error: Oops! An error occured while making the request to create the Theme.

### Expected Behavior

Theme get created

### Steps to Reproduce

1. Link a salla partner account to a github organization
2. login to the account from salla cli
3. run : `salla theme create`
4. follow Cli instructions

### Salla Info

salla cli version: 3.2.1
npm version: 9.7.1
node version: v18.17.0

**Comment by aimdexter** [comment]
Hello support

**Comment by MhndMousa** [comment]
I faced the same problem before trying to create a theme with an organization account. 

For now you can only create a theme or an app with a user account and not an organization.

I think they should add it as a feature at some point!

**Comment by aimdexter** [comment]
I did not get any answer, why the issue is marked as closed !!!
