### ISSUE TITLE
موقع https://salla.sa/med.stor

### ISSUE THREAD

**Issue by medoasiri** [SallaApp/Salla-CLI#35]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

App

### Current Behavior

#https://salla.sa/med.stor

### Expected Behavior

https://salla.sa/med.stor

### Steps to Reproduce

>  @``

### Salla Info

موقع https://salla.sa/med

> .stor

**Comment by Nabute** [comment]
@medoasiri please follow the right steps to submit an issue so that we can understand and reproduce your case in our machine and come up with a solution.
