### ISSUE TITLE
bug: Error on previewing theme

### ISSUE THREAD

**Issue by CodeCurosity** [SallaApp/Salla-CLI#37]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

It was working just fine but i think i committed to github from VS Code or something, after it keep throwing this error whenever i try to preview theme.

` WARN  Tag 1.0.16 already exists
 WARN  Authorization Error: 
 ERROR  Tag 1.0.16 already exists
 ERROR  The CLI failed to request preview for the Theme. Try again later.
Error: The CLI failed to request preview for the Theme. Try again later.
                     
 ERROR  Error: The CLI failed to request preview for the Theme. Try again later.
`

### Expected Behavior

Should preview.

### Steps to Reproduce

Preview theme

### Salla Info

version: 3.2.1
npm version: 9.5.0
node version: v18.14.2
php version: 8.2.9
os: darwin
os version: 22.1.0
user id: 210017680
uuid: A2656077-F8BB-4EF1-AE0B-E2665389AF83

**Comment by Nabute** [comment]
please run `salla login`  to authorize your account and then run `salla theme preview`

**Comment by 3lawix9** [comment]
I fix it with doing Salla theme create 
Then clone the same repo from github (Same project that you working on ) 
And works fine

**Comment by 3lawix9** [comment]
First, try to see if you are in the correct folder. I do cd Sallatheme, which is the file with all Salla files, and it works.

**Comment by Morebenk** [comment]
> please run `salla login` to authorize your account and then run `salla theme preview`

I tried it, but didn't work :( same issue.

**Comment by Nabute** [comment]
> > please run `salla login` to authorize your account and then run `salla theme preview`
> 
> I tried it, but didn't work :( same issue.

can you please share the steps to reproduce your scenario?

**Comment by jalmatari** [comment]
if you still face the issue try to make any changes on the twig files, even space, then push changes to github, everything should work fine with you

**Comment by mohmad-sawan** [comment]
First, check whether the folder you are in is the same directory as the theme or not, go to the same folder you cloned or create the theme on it.
Second, if the salle CLI is running turn it off and try again.

**Comment by yousseffathy110** [comment]
Run the following command to update the Salla CLI globally:
 `npm update @salla.sa/cli -g` 
and **Ensure** you open the application using **Microsoft Edge**.
This solution works as expected.
