### ISSUE TITLE
bug: .github/workflows/build-assets.yaml: No jobs were run

### ISSUE THREAD

**Issue by CodeCurosity** [SallaApp/Salla-CLI#38]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

Everytime i preview on local machine using CLI and everytime i make changes in Salla partners theme page i get these emails from github, .github/workflows/build-assets.yaml: No jobs were run and it doesn't sync with local machine when i preview again it gives error that tag already exists.

### Expected Behavior

It shouldn't throw error and should sync with local.

### Steps to Reproduce

make changes in theme in partner area.

### Salla Info

version: 3.2.1
npm version: 9.5.0
node version: v18.14.2
php version: 8.2.9
os: darwin
os version: 22.1.0
user id: 210017680
uuid: A2656077-F8BB-4EF1-AE0B-E2665389AF83

**Comment by jalmatari** [comment]
1- about 'emails from github', try to remove the `.github` folder
2- about the `tag already exists` make any changes on the twig files, even space or something, then push changes to github, everything should work fine with you
