### ISSUE TITLE
[docs]: typo

### ISSUE THREAD

**Issue by anon-phantom** [SallaApp/Salla-CLI#39]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

App

### Current Behavior

[page tail](https://docs.salla.dev/docs/twilight-themes-documentation/3ac843cae76a2-overview#basic-configuration)

![image](https://github.com/SallaApp/Salla-CLI/assets/71615064/b27952c8-78d6-4ad1-96b9-3bf7db634a37)

### Expected Behavior

null

### Steps to Reproduce

* currencies

### Salla Info

[Salla info]

version: 3.2.1
npm version: 9.7.2
node version: v18.6.0
php version: 8.2.8
os: win32
os version: 10.0.22621
user id: 2099118681
uuid: A7EBA3AA-04D5-4583-960F-E240A0AA76D1

**Comment by nabiloo19** [comment]
@anon-phantom thank you for reporting the typo on the Twilight documentation

Kindly, use [this space](https://github.com/SallaApp/Salla-CLI/) only for Salla CLI issues. For any other related issues on your apps and themes, join our Developer Community on [Telegram](https://t.me.salladev)
