### ISSUE TITLE
Error while copying Express project files

### ISSUE THREAD

**Issue by mutairibassam** [SallaApp/Salla-CLI#4]
There is an error while copying Express project files, please refer to the attached screenshot.

<img width="1676" alt="Screen Shot 1443-09-30 at 5 10 30 PM" src="https://user-images.githubusercontent.com/54819958/166150654-b9cf066c-9877-4a4b-aac8-e34f7cc19d77.png">

**Comment by KernelCode** [comment]
Thank you for reporting this bug .. it's been fixed now .. can you try installing the latest Salla CLI version using this command : 

`npm install  -g @salla.sa/cli@latest`

check you have the latest version : 

`Version: 1.1.7`
