### ISSUE TITLE
[docs]: endpoint url error

### ISSUE THREAD

**Issue by anon-phantom** [SallaApp/Salla-CLI#40]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [ ] v1.x

### Salla CLI issue Type

App

### Current Behavior

![image](https://github.com/SallaApp/Salla-CLI/assets/71615064/d171e97c-1b67-4449-807b-b2c89d83ec90)

@ [webhooks#register-endpoint-1](https://docs.salla.dev/docs/merchant/fe18b08f8cf87-webhooks#register-endpoint-1)

```shell

404 Not Found
{
  "status": 404,
  "success": false,
  "error": {
    "code": "error",
    "message": ""
  }
}

```

### Expected Behavior

null

### Steps to Reproduce

* https://api.salla.dev/admin/v2/webhooks/subscribe

### Salla Info

[Salla info]

version: 3.2.1
npm version: 9.7.2
node version: v18.6.0
php version: 8.2.8
os: win32
os version: 10.0.22621
user id: 2099118681
uuid: A7EBA3AA-04D5-4583-960F-E240A0AA76D1

**Comment by Nabute** [comment]
can you please provide more detail on how I can reproduce your scenario?

**Comment by nabiloo19** [comment]
It seems working fine

I have linked an image showcasing the successfulness of the code written on the documentation:

https://docs.salla.dev/docs/merchant/fe18b08f8cf87-webhooks#regsiter-webhooks

View the image via this link: https://share.cleanshot.com/qPGXmPXx

You may use the following cURL to check:

```
curl --request POST \
  --url https://api.salla.dev/admin/v2/webhooks/subscribe \
  --header 'Accept: application/json' \
  --header 'Authorization: YOUR_ACCESS_TOKEN' \
  --header 'Content-Type: application/json' \
  --data '{
  "name": "Order Updated Webhook with Payment",
  "event": "order.updated",
  "version": "2",
  "rule": "payment_method = mada",
  "url": "https://webhook.site/168eb569-cbc5-40ad-8940-3dcd8044xxx",
  "security_strategy": "token",
  "secret": "4d7dac8e688eca1c1xxxx"
}'
```

**Comment by anon-phantom** [comment]
the endpoit is working fine, the issue is wrong url in documentation page

- current url -> `https://api.salla.dev/admin/v2/admin/v2/webhooks/subscribe`
- correct url -> `https://api.salla.dev/admin/v2/webhooks/subscribe`


![](https://user-images.githubusercontent.com/71615064/270214652-d171e97c-1b67-4449-807b-b2c89d83ec90.png)

**Comment by nabiloo19** [comment]
Thank you for your feedback, we’ll make sure it is correctly reflected.

Appreciate the help
