### ISSUE TITLE
bug: Preview Salla theme with editor shows 500 page Error! 

### ISSUE THREAD

**Issue by 3lawix9** [SallaApp/Salla-CLI#41]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

Just when i preview theme without editor it works great 
But with Salla editor it shows 500 Error page : 500
💔 IT'S ME, NOT YOU 

### Expected Behavior

shows the all components in the editor and the page 

### Steps to Reproduce

Just fix it 

### Salla Info

version: 3.2.1       
npm version: 9.8.0
node version: v20.5.0
php version: 8.2.10
os: win32
os version: 10.0.19045
user id: 1908693027
uuid: 58927197-C79C-4042-9C91-80CE2963F10E

**Comment by Nabute** [comment]
hello @3lawix9 thank you for your report. Can you please provide a detailed steps to reproduce your error? Because, everything is working fine from my side
