### ISSUE TITLE
abug:  An error  can't login using salla login command

### ISSUE THREAD

**Issue by abdulrhman-developer0** [SallaApp/Salla-CLI#42]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [ ] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

![Screenshot_45](https://github.com/SallaApp/Salla-CLI/assets/86319898/721587a1-168c-45d4-a90b-88d5721e272f)

### Expected Behavior

login to salla partners  to mange primary operations

### Steps to Reproduce

`salla login` or `npx salla login`
![Screenshot_46](https://github.com/SallaApp/Salla-CLI/assets/86319898/8aefac6c-588b-4bb2-83d1-9d3fd67be21b)

### Salla Info

version: 3.2.1
npm version: 9.5.1
node version: v18.16.0
php version: 8.2.4
os: win32
os version: 10.0.14393
user id:
uuid:

**Comment by Nabute** [comment]
is it still happening?

**Comment by esraaeyad123** [comment]
How did you dissolve?

**Comment by Nabute** [comment]
It's resolved now. I suggest you try it again.

**Comment by esraaeyad123** [comment]
How

**Comment by hesx10** [comment]
i have a same problem now
