### ISSUE TITLE
abug: An error can't login using salla login command #42

### ISSUE THREAD

**Issue by esraaeyad123** [SallaApp/Salla-CLI#44]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

![image](https://github.com/SallaApp/Salla-CLI/assets/47371491/8de53e99-f26a-4a97-be80-1172ed2932d5)

### Expected Behavior

login to salla partners to mange primary operations

### Steps to Reproduce

salla login or npx salla login

### Salla Info

[Salla info]

version: 3.2.1
npm version: 10.1.0
node version: v20.9.0
php version: 8.1.13
os: win32
os version: 10.0.19045
user id:
uuid:

**Comment by Nabute** [comment]
I am pretty sure it will work if you try it again. Sometimes the node processor glitches. If it's not resolved, let me know so that I can further investigate.
