### ISSUE TITLE
bug: Can't install Salla CLI

### ISSUE THREAD

**Issue by hasanalkaf3** [SallaApp/Salla-CLI#45]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

App

### Current Behavior

I have installed the latest versions of npm, nodejs, php and composer, then tried to install Salla CLI, but it gives me an error:
![Error](https://github.com/SallaApp/Salla-CLI/assets/98897848/b31c724d-57f0-4270-8f2e-5c33fc00178e)

After I give it a permission it got stuck downloading:
![Errorstuck](https://github.com/SallaApp/Salla-CLI/assets/98897848/eb805eae-0191-40e2-8c99-b978c8b7ecb5)

### Expected Behavior

Installed without any problem.

### Steps to Reproduce

Run this command:
`sudo npm install @salla.sa/cli -g`

### Code Reproduction URL

https://salla.dev/blog/meet-salla-cli/error/not-found, this link doesn't work

### Salla Info

Salla is not installed.

### Additional Information

- OS: Linux EndeavourOS (Arch)
- Kernel: 6.6.1-arch1-1-g14

**Comment by Nabute** [comment]
@hasanalkaf3 from where I see it, it's related to your internet. Can you please check your connection and try again.

**Comment by hasanalkaf3** [comment]
No, there is no problem with the internet
(100 Mbps)

**Comment by hasanalkaf3** [comment]
Finally It's Work
![Screenshot_20231123_154145](https://github.com/SallaApp/Salla-CLI/assets/98897848/9eac7b9e-2e04-49ef-8cb1-e62f54346413)
