### ISSUE TITLE
bug:  i couldn't open theme preview  

### ISSUE THREAD

**Issue by kyrillos16** [SallaApp/Salla-CLI#49]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

when am trying to open the preview by run command `salla theme p` i got this error 

`
 ERROR  The CLI failed to request preview for the Theme. Try again later.
Error: The CLI failed to request preview for the Theme. Try again later.

 ERROR  Error: The CLI failed to request preview for the Theme. Try again later.
`

### Expected Behavior

it should work and open the theme preview

### Steps to Reproduce

- salla login 
- salla theme p 

### Salla Info

[Salla info]

version: 1.4.62
npm version: 10.1.0
node version: v20.9.0
'php' is not recognized as an internal or external command,
operable program or batch file.

 ERROR  Error: Command failed: php -v
'php' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kyrillos16** [comment]
![2023-12-17_15-39](https://github.com/SallaApp/Salla-CLI/assets/146574556/ee75ee4b-02c9-4e6f-bec4-cf7ba5a20521)
the GitHub account linked

**Comment by KareemElebasy** [comment]
i have the same issues now

**Comment by hesham156** [comment]
i have the same issues now

**Comment by mohamedeld** [comment]
Create your repository in your GitHub and they will go to Partner, choose my theme import repository, then select the repository you created
