### ISSUE TITLE
[bug] duplicate lines in selection options

### ISSUE THREAD

**Issue by mutairibassam** [SallaApp/Salla-CLI#5]
There is unexpected duplication when I navigate only from top to down to select an option. Please see attached.

- Example 1:
<img width="1677" alt="Screen Shot 1443-10-09 at 7 08 44 PM" src="https://user-images.githubusercontent.com/54819958/167674613-aa01b86d-4eda-40fb-a20a-d5db86a8b41c.png">

- Example 2:
<img width="1673" alt="Screen Shot 1443-10-09 at 7 09 04 PM" src="https://user-images.githubusercontent.com/54819958/167674683-5d29f1dd-889a-46c6-b2c5-00315329f862.png">

**Comment by KernelCode** [comment]
Thank you for reporting this bug .. it's been fixed now .. can you try installing the latest Salla CLI version using this command :

npm install -g @salla.sa/cli@latest
