### ISSUE TITLE
bug: Not able to crate a webhook using Salla CLI

### ISSUE THREAD

**Issue by Aji-DN** [SallaApp/Salla-CLI#50]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [ ] v1.x

### Salla CLI issue Type

App

### Current Behavior

The create webhook command is not working for me.

$ salla app create-webhook app.installed

this command gives below error

 ERROR  Error: Oops! An error occured. Please enter a valid webhook name. Example: 'app.installed'

### Expected Behavior

The command should install a ebhook

### Steps to Reproduce

$ salla app create-webhook app.installed
<img width="610" alt="image" src="https://github.com/SallaApp/Salla-CLI/assets/137489026/8b0851c0-9680-4a35-af07-324a175e6b69">

### Salla Info

[Salla info]

version: 3.2.1
npm version: 10.2.3
node version: v20.10.0
php version: 7.2.34
os: win32
os version: 10.0.22621
user id: 856923266
uuid: 0FA48B9F-5FFA-4C27-8296-9F923915C333

**Comment by Nabute** [comment]
Hello @Aji-DN Thank you for your request. The issue is regarding your usage.

You are using the CLI to create app without providing the right arguments `--webhook-name`

The right way to use is

```bash
salla app create-webhook --webhook-name=app.installed
```

Note: Unfortunately, `app.installed` is not allowed to use since it's used for internal usage.

**Comment by Aji-DN** [comment]
Thank you for the clarification,

I was following this documentation.

[image: image.png]


And still the webhook command is not successful  with the updated command.


[image: image.png]

**Comment by Nabute** [comment]
Well, when a webhook name is valid it has to comply with 2 rules
1. It has to take a structure of 
```bash
--webhook-name=foo.bar
```

2. The provided name has to be out of the internally used names, and `app.installed` is internally used so you need to find a better name.

Please take a look at the image below
![image](https://github.com/SallaApp/Salla-CLI/assets/40380324/96b2d89e-d2ee-4079-8add-943bd1a50a6e)
