### ISSUE TITLE
bug: sallatheme

### ISSUE THREAD

**Issue by Al-Ashger** [SallaApp/Salla-CLI#51]
### Prerequisites

- [ ] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

# A first-level heading
### Expected Behavior

[README.md](https://github.com/SallaApp/Salla-CLI/files/13754515/README.md)

### Steps to Reproduce

[README.md](https://github.com/SallaApp/Salla-CLI/files/13754517/README.md)

### Code Reproduction URL

https://github.com/Al-Ashger/ffff

### Salla Info

{"salla":{"access_token":"SP_AawMWdvdoGLk9VArgdU2zVE7kv2AP39YDYpKcY9P9EQId0k6rltFu","lastCheck":1703434943.529,"user":{"id":1413618154,"first_name":"Mohammad","last_name":"Alrazmy","type":"person","email":"rzamy043@gmail.com","mobile_code":null,"mobile_country_code":null,"mobile":null,"verified":true,"id_verified":true,"id_require_update":false,"two_factor":false,"role":"company-admin","token":"SP_AawMWdvdoGLk9VArgdU2zVE7kv2AP39YDYpKcY9P9EQId0k6rltFu","language":"ar","status":{},"created_at":"2023-08-17T23:46:15.000000Z","updated_at":"2023-12-15T12:11:44.000000Z","is_admin":false,"is_owner":true,"is_test":false,"github_authorized":true,"is_frozen":false,"force_id_verification":false,"private_apps_limit":1,"disable_private_apps":false,"tax_number":null,"permissions":["Create App","show-dashboard","manage-apps","manage-demo-stores","manage-coupons","manage-company-settings","manage-tax-number","manage-id-verification","manage-payment-methods","manage-payouts","manage-webhook-logs","manage-themes","manage-faq","manage-support","manage-employees","manage-reports","manage-invoices","manage-development-stores","manage-services","services-create","services-update","services-delete","manage-orders","manage-security","manage-settings","services-preview","manage-notifications-center","manage-development-stores"],"is_theme_allowed":true,"bio":{"ar":null,"en":null},"github_user":{"login":"Al-Ashger","id":91567380,"avatar_url":"https://avatars.githubusercontent.com/u/91567380?v=4","url":"https://api.github.com/users/Al-Ashger","name":null,"email":null},"company":{"id":448487207,"name":"Mohammad Alrazmy","email":"rzamy043@gmail.com","tax_number":null,"street_name":null,"house_number":null,"post_code":null,"mobile_code":null,"mobile_country_code":null,"mobile":null,"is_test":false,"created_at":"2023-08-17T23:46:15.000000Z","updated_at":"2023-12-22T16:22:22.000000Z","bio":{"ar":null,"en":null},"country":null,"city":null,"avatar":null},"avatar":null}},"github":{},"uuid":"d860d3c5-e5b0-4299-9133-8cb998d9a182","vscode_extension_installed":"installed"}

**Comment by Nabute** [comment]
@Al-Ashger thank you for the report. Can you please follow the issue guideline and provide all the necessary information in the process so that we will not be redirected to another page or the information can be found in here.

Thanks in advance.

**Comment by Al-Ashger** [comment]
> ### Prerequisites
> * [ ]  I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.
> 
> ### SallaCLI Version
> * [x]  v1.x
> 
> ### Salla CLI issue Type
> Theme
> 
> ### Current Behavior
> # A first-level heading
> ## A second-level heading
> ### A third-level heading
> ### Expected Behavior
> [README.md](https://github.com/SallaApp/Salla-CLI/files/13754515/README.md)
> 
> ### Steps to Reproduce
> [README.md](https://github.com/SallaApp/Salla-CLI/files/13754517/README.md)
> 
> ### Code Reproduction URL
> https://github.com/Al-Ashger/ffff
> 
> ### Salla Info
> {"salla":{"access_token":"SP_AawMWdvdoGLk9VArgdU2zVE7kv2AP39YDYpKcY9P9EQId0k6rltFu","lastCheck":1703434943.529,"user":{"id":1413618154,"first_name":"Mohammad","last_name":"Alrazmy","type":"person","email":"[rzamy043@gmail.com](mailto:rzamy043@gmail.com)","mobile_code":null,"mobile_country_code":null,"mobile":null,"verified":true,"id_verified":true,"id_require_update":false,"two_factor":false,"role":"company-admin","token":"SP_AawMWdvdoGLk9VArgdU2zVE7kv2AP39YDYpKcY9P9EQId0k6rltFu","language":"ar","status":{},"created_at":"2023-08-17T23:46:15.000000Z","updated_at":"2023-12-15T12:11:44.000000Z","is_admin":false,"is_owner":true,"is_test":false,"github_authorized":true,"is_frozen":false,"force_id_verification":false,"private_apps_limit":1,"disable_private_apps":false,"tax_number":null,"permissions":["Create App","show-dashboard","manage-apps","manage-demo-stores","manage-coupons","manage-company-settings","manage-tax-number","manage-id-verification","manage-payment-methods","manage-payouts","manage-webhook-logs","manage-themes","manage-faq","manage-support","manage-employees","manage-reports","manage-invoices","manage-development-stores","manage-services","services-create","services-update","services-delete","manage-orders","manage-security","manage-settings","services-preview","manage-notifications-center","manage-development-stores"],"is_theme_allowed":true,"bio":{"ar":null,"en":null},"github_user":{"login":"Al-Ashger","id":91567380,"avatar_url":"[https://avatars.githubusercontent.com/u/91567380?v=4","url":"https://api.github.com/users/Al-Ashger","name":null,"email":null},"company":{"id":448487207,"name":"Mohammad](https://avatars.githubusercontent.com/u/91567380?v=4%22,%22url%22:%22https://api.github.com/users/Al-Ashger%22,%22name%22:null,%22email%22:null%7D,%22company%22:%7B%22id%22:448487207,%22name%22:%22Mohammad) Alrazmy","email":"[rzamy043@gmail.com](mailto:rzamy043@gmail.com)","tax_number":null,"street_name":null,"house_number":null,"post_code":null,"mobile_code":null,"mobile_country_code":null,"mobile":null,"is_test":false,"created_at":"2023-08-17T23:46:15.000000Z","updated_at":"2023-12-22T16:22:22.000000Z","bio":{"ar":null,"en":null},"country":null,"city":null,"avatar":null},"avatar":null}},"github":{},"uuid":"d860d3c5-e5b0-4299-9133-8cb998d9a182","vscode_extension_installed":"installed"}
> 
> ### Additional Information
> _No response_
