### ISSUE TITLE
bug: The Theme was not created

### ISSUE THREAD

**Issue by KareemElebasy** [SallaApp/Salla-CLI#52]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [ ] v1.x

### Salla CLI issue Type

App

### Current Behavior

Failed to create repository, it may be already exists or you are using organization github account.

### Expected Behavior

Failed to create repository, it may be already exists or you are using organization github account.

### Steps to Reproduce

Failed to create repository, it may be already exists or you are using organization github account.

### Salla Info

Failed to create repository, it may be already exists or you are using organization github account.

### Additional Information

Failed to create repository, it may be already exists or you are using organization github account.

**Comment by Nabute** [comment]
GitHub organization accounts are not supported yet. Please use GitHub personal account.
