### ISSUE TITLE
 bug: authentication faild when i write this cli command salla theme create 

### ISSUE THREAD

**Issue by Hosam-Alkulaby** [SallaApp/Salla-CLI#53]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [ ] v1.x

### Salla CLI issue Type

App

### Current Behavior

can you give us the solution please

### Expected Behavior

..

### Steps to Reproduce

..

### Salla Info

..

### Additional Information

..

**Comment by Nabute** [comment]
Please try it again, it may be caused by the internet connection
