### ISSUE TITLE
The node_modules folder is not found. Please run `npm install`

### ISSUE THREAD

**Issue by hindbsdev** [SallaApp/Salla-CLI#57]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

![لقطة شاشة 2024-03-05 225555](https://github.com/SallaApp/Salla-CLI/assets/161594799/e50cacd2-20be-46ca-811a-c7d356d29948)

### Expected Behavior

i don't know what's the problem or what happened or why?

### Steps to Reproduce

after create the theme everthing was great but suddenly i can't preview salla theme 

### Salla Info

![لقطة شاشة 2024-03-05 225827](https://github.com/SallaApp/Salla-CLI/assets/161594799/6d24caa2-261b-4dd1-a189-5817f731111d)

**Comment by Nabute** [comment]
please run `npm install` before previewing
