### ISSUE TITLE
bug: salla login error on windows

### ISSUE THREAD

**Issue by moomoh** [SallaApp/Salla-CLI#59]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [ ] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

when using salla login i get the following error 
⠼ Waiting for authentication ...
 ERROR  Error: spawn UNKNOWN

C:\Users\ra>salla login

        _____       _ _          _____ _      _____
       / ____|     | | |        / ____| |    |_   _|
      | (___   __ _| | | __ _  | |    | |      | |
       \___ \ / _` | | |/ _` | | |    | |      | |
       ____) | (_| | | | (_| | | |____| |____ _| |_
      |_____/ \__,_|_|_|\__,_|  \_____|______|_____|

                     Version: 3.2.1
        The Official Salla Command Line Interface

 INFO  Read the docs: https://github.com/SallaApp/Salla-CLI/
 INFO  Support and bugs: https://github.com/SallaApp/Salla-CLI/issues

 INFO  To complete the login process, you will be redirected to your browser to signin with your Salla Partners account.

⠼ Waiting for authentication ...
 ERROR  Error: spawn UNKNOWN

 WARN  If this error persists, please visit https://github.com/SallaApp/salla-cli/issues and submit an issue.

### Expected Behavior

This is a fresh salla cli installation on windows 11 
on using salla login the procedure doesn't go through to open the link for salla partners to login in , instead all what happens it keeps flashing in waiting for authentication and then shows error spawn unknown

what is the solution for this 

⠼ Waiting for authentication ...
 ERROR  Error: spawn UNKNOWN

### Steps to Reproduce

C:\Users\ra>salla login

        _____       _ _          _____ _      _____
       / ____|     | | |        / ____| |    |_   _|
      | (___   __ _| | | __ _  | |    | |      | |
       \___ \ / _` | | |/ _` | | |    | |      | |
       ____) | (_| | | | (_| | | |____| |____ _| |_
      |_____/ \__,_|_|_|\__,_|  \_____|______|_____|

                     Version: 3.2.1
        The Official Salla Command Line Interface

 INFO  Read the docs: https://github.com/SallaApp/Salla-CLI/
 INFO  Support and bugs: https://github.com/SallaApp/Salla-CLI/issues

 INFO  To complete the login process, you will be redirected to your browser to signin with your Salla Partners account.

⠼ Waiting for authentication ...
 ERROR  Error: spawn UNKNOWN

 WARN  If this error persists, please visit https://github.com/SallaApp/salla-cli/issues and submit an issue.

### Salla Info

[Salla info]

version: 3.2.1
npm version: 10.5.0
node version: v20.11.1
php version: 8.3.4
os: win32
os version: 10.0.22621
user id:
uuid:

**Comment by Nawafhw** [comment]
Hi there Please try disabling the firewall and then try again.
