### ISSUE TITLE
[Error] An error while creating an application through Salla-CLI

### ISSUE THREAD

**Issue by mutairibassam** [SallaApp/Salla-CLI#6]
**Description**
The error shows after selecting framework step for both existing application or new applications.

**Steps to reproduce**
- Open terminal/CMD.
- Run command `salla app create`
- Select an existing application or new one.
- Select any framework (Express or Laravel) both has the same issue.
- See error.

**Expected result**
Go to next step or create an application with the selected framework.

**Actual result**
Error message shows: *ERROR  Oops! There is an error while creating your App .*

**Details**
- Salla version: 1.2.2
- OS: macOS
- Command Language: Z shell (zsh)

**Screenshot**
![Screen Shot 1443-12-21 at 7 14 13 AM](https://user-images.githubusercontent.com/54819958/179895477-440f98bf-5843-47bf-b5bc-b24028394049.png)

**Comment by KernelCode** [comment]
Hi Mutairi,
download the latest version from npm ..
