### ISSUE TITLE
I can't login to Salla-CLI when open new tab on browser!!

### ISSUE THREAD

**Issue by SifouElYasLakhHa** [SallaApp/Salla-CLI#7]
there is a screenshot of issues on cmd windowes
[https://prnt.sc/xs12D_6_AWG_](url)
https://prnt.sc/zYU5m1WfhQ6e
I hope I gave an full desc about the problem
please fixed it soon!

**Comment by KernelCode** [comment]
hi , 
it's fixed now .. sorry to be late .. it was a configration problem .. you can try now and login
