### ISSUE TITLE
bug: The CLI failed to request preview for the Theme. Try again later.

### ISSUE THREAD

**Issue by nawafAlkhadidi** [SallaApp/Salla-CLI#78]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/SallaApp/Salla-CLI/issues) that already report this problem, without success.

### SallaCLI Version

- [X] v1.x

### Salla CLI issue Type

Theme

### Current Behavior

raqman % salla theme preview        

        _____       _ _          _____ _      _____ 
       / ____|     | | |        / ____| |    |_   _|
      | (___   __ _| | | __ _  | |    | |      | |  
       \___ \ / _` | | |/ _` | | |    | |      | |  
       ____) | (_| | | | (_| | | |____| |____ _| |_ 
      |_____/ \__,_|_|_|\__,_|  \_____|______|_____|
    
                     Version: 3.2.2
        The Official Salla Command Line Interface
                     
 INFO  Read the docs: https://github.com/SallaApp/Salla-CLI/ 
 INFO  Support and bugs: https://github.com/SallaApp/Salla-CLI/issues 
                     
 INFO  run checks: 
     ✓ twilight.json was found.
     ✓ Github account is linked.
     ✓ Theme ID exists.
     ✓ The theme folder is linked to GitHub repository.
                     
 INFO  Getting your demo stores from your account...
                     
Listed below are the stores assoicated with your Salla Partners account ..
You can either select an existing store or create a new store in simple steps
                     
? Select the store you want to install the theme on:  reqman3
                     
 INFO  Assets URL : http://localhost:8000
 INFO  Live reload URL : ws://localhost:8001
                     
 DONE  Hooray! WebSocket & Assets servers are currently running.

You can skip this question by adding --with-editor
                     
✔ Do you want to open the theme in the editor? · no
                     
 ERROR  The CLI failed to request preview for the Theme. Try again later.
Error: The CLI failed to request preview for the Theme. Try again later.
                     
 ERROR  Error: The CLI failed to request preview for the Theme. Try again later.
                     
 WARN  If this error persists, please visit https://github.com/SallaApp/salla-cli/issues and submit an issue.

### Expected Behavior

when i run this   salla theme preview         

### Steps to Reproduce

 raqman % salla theme preview        

### Salla Info

[Salla info]

**Comment by shamskholani2020** [comment]
@nawafAlkhadidi Hello Nawaf, How you doing?, did you solve it?
